fix patch for building CommunityMQTT kit with sedona
Before following error happend:

/tmp/ccw5eA8g.o: In function `messageArrived':
communityMQTT_Worker.c:(.text+0x20): undefined reference to `pthread_getspecific'
/tmp/ccw5eA8g.o: In function `makeThreadKey':
communityMQTT_Worker.c:(.text+0x8bb): undefined reference to `pthread_key_create'
/tmp/ccw5eA8g.o: In function `workerThreadFunc':
communityMQTT_Worker.c:(.text+0x10fd): undefined reference to `pthread_setspecific'
communityMQTT_Worker.c:(.text+0x11aa): undefined reference to `pthread_setspecific'
/tmp/ccw5eA8g.o: In function `communityMQTT_Worker_startSession':
communityMQTT_Worker.c:(.text+0x1280): undefined reference to `pthread_once'
communityMQTT_Worker.c:(.text+0x1353): undefined reference to `pthread_create'
communityMQTT_Worker.c:(.text+0x1364): undefined reference to `pthread_detach'
collect2: error: ld returned 1 exit status
**
** 'FATAL: compileunix /home/developer/sedonadev/bin/svm

According to pthread_create man page gcc requires '-pthread'.