update README
0. fix types in command

1. communityMQTT kit should be build before makeunixvm, otherwise
it complains about unknown kit:

$ makeunixvm
  Removing "/home/developer/sedonadev/build/temp/generic-unix"
  Removing "/home/developer/sedonadev/build/temp/generic-unix/.par"
  Removing "/home/developer/sedonadev/build/temp/generic-unix/.par/svm"
  InitStagePlatform [generic-unix.xml]
/home/developer/sedonadev/platforms/src/generic/unix/generic-unix.xml:7: Missing kit dependency 'communityMQTT 1.0+'
*** FAILED with 1 error(s) and 0 warning(s) ***
**
** 'FATAL: compilekit /home/developer/sedonadev/platforms/src/generic/unix/generic-unix.xml -outDir /home/developer/sedonadev/build/temp/generic-unix'
** FAILED [/home/developer/sedonadev/bin/svm]
**

Error:  Could not find platform manifest: /home/developer/sedonadev/build/temp/generic-unix/.par/platformManifest.xml